worktree-path = "~/.agents/worktrees/{{ repo }}/{{ branch | sanitize }}"
skip-commit-generation-prompt = true

[switch.picker]
pager = "delta --paging=never --width=$COLUMNS"

[post-start]
copy = "wt step copy-ignored"
