#!/usr/bin/env bash

file_name="${1:-Brewfile}"

brew bundle dump -f --formula --cask --tap --mas --file="$(pwd)/$file_name"

brew bundle cleanup --force && brew bundle --no-lock --file="$(pwd)/$file_name"
